version: '1.0'



services:


  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: network-parser
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/network-parser
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - 'minione_data:/data'
    environment:
      - MINIO_ROOT_USER=network
      - MINIO_ROOT_PASSWORD=networkpass
      - MINIO_DEFAULT_BUCKET=temp

volumes:
  minione_data:
    driver: local