
# Server configuration
server:
  port: 8765

# File upload properties and database configuration
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/network-parser
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

# Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

# Minio configuration
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:OtwRLldr3MVNdgPnNTRq}
  secret-key: ${MINIO_SECRET_KEY:SDVwPNDnPPfPnZLvBXkF8Uw0Xa8QicgwZUXMzGZ7}
  backet-name: ${MINIO_BACKET_NAME:name}
  #  expiration-time: 2 days in milliseconds for the pre-signed URLs
  expirationTime: ${MINIO_EXPIRATION_TIME:600000}

