
# Server configuration
server:
  port: ${SERVER_PORT:6565}

# File upload properties and database configuration
spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/minioNetworkParser}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

# Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

# Minio configuration
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:izXnkWHLzHhokgRSEs7X}
  secret-key: ${MINIO_SECRET_KEY:LuhelCRDncTaa0u22LiF3GYbyKmagwr0KyAmCUx2}
  backet-name: ${MINIO_BACKET_NAME:temp}
  #  expiration-time: 2 days in milliseconds for the pre-signed URLs
  expirationTime: ${MINIO_EXPIRATION_TIME:600000}

